name: PracticeGHA
on: 
  push:
    branches:
      - main
      - deploy
      - 'release/**'
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build setup
        run: echo "Build setup for, ${{ vars.My_Name }}"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Tests setup
        run: echo "Tests setup for, ${{ secrets.Auth_Token }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deployment setup
        run: echo "Deployment setup completed"
    
      
