name: PracticeGHA
on: workflow_dispatch
jobs:
  practice:
    runs-on: ubuntu-latest
    steps:
      - name: Practice GHA
        run: |
          echo "Practicing GitHub Actions-line 1"
          echo "Practicing GitHub Actions-line 1"
      
